package fr.cpbstats.model;

// Generated 29 juin 2015 23:26:12 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exercice generated by hbm2java
 */
@Entity
@Table(name = "exercice")
public class Exercice implements java.io.Serializable {

    private ExerciceId id;
    private Utilisateur utilisateur;
    private TypeExercice typeExercice;
    private String data;
    private Date date;

    public Exercice() {}

    public Exercice(ExerciceId id, Utilisateur utilisateur, TypeExercice typeExercice) {
        this.id = id;
        this.utilisateur = utilisateur;
        this.typeExercice = typeExercice;
    }

    public Exercice(ExerciceId id, Utilisateur utilisateur, TypeExercice typeExercice, String data,
            Date date) {
        this.id = id;
        this.utilisateur = utilisateur;
        this.typeExercice = typeExercice;
        this.data = data;
        this.date = date;
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
            @AttributeOverride(name = "typeExerciceId", column = @Column(name = "type_exercice_id",
                    nullable = false)) })
    public ExerciceId getId() {
        return this.id;
    }

    public void setId(ExerciceId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "utilisateur_id", nullable = false)
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }

    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "type_exercice_id", nullable = false, insertable = false, updatable = false)
    public TypeExercice getTypeExercice() {
        return this.typeExercice;
    }

    public void setTypeExercice(TypeExercice typeExercice) {
        this.typeExercice = typeExercice;
    }

    @Column(name = "data", length = 45)
    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date", length = 19)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

}
