package fr.cpbstats.model;

// Generated 13 juil. 2015 22:22:31 by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ObjectifExercice generated by hbm2java
 */
@Entity
@Table(name = "objectif_exercice")
public class ObjectifExercice implements java.io.Serializable {

    private Integer id;
    private TypeExercice typeExercice;
    private Objectif objectif;
    private String data;
    private String date;
    private Boolean recurrentSemaine;
    private Boolean recurrentMois;

    public ObjectifExercice() {}

    public ObjectifExercice(TypeExercice typeExercice, Objectif objectif) {
        this.typeExercice = typeExercice;
        this.objectif = objectif;
    }

    public ObjectifExercice(TypeExercice typeExercice, Objectif objectif, String data, String date,
            Boolean recurrentSemaine, Boolean recurrentMois) {
        this.typeExercice = typeExercice;
        this.objectif = objectif;
        this.data = data;
        this.date = date;
        this.recurrentSemaine = recurrentSemaine;
        this.recurrentMois = recurrentMois;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "type_exercice_id", nullable = false)
    public TypeExercice getTypeExercice() {
        return this.typeExercice;
    }

    public void setTypeExercice(TypeExercice typeExercice) {
        this.typeExercice = typeExercice;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "objectif_id", nullable = false)
    public Objectif getObjectif() {
        return this.objectif;
    }

    public void setObjectif(Objectif objectif) {
        this.objectif = objectif;
    }

    @Column(name = "data", length = 45)
    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

    @Column(name = "date", length = 45)
    public String getDate() {
        return this.date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    @Column(name = "recurrent_semaine")
    public Boolean getRecurrentSemaine() {
        return this.recurrentSemaine;
    }

    public void setRecurrentSemaine(Boolean recurrentSemaine) {
        this.recurrentSemaine = recurrentSemaine;
    }

    @Column(name = "recurrent_mois")
    public Boolean getRecurrentMois() {
        return this.recurrentMois;
    }

    public void setRecurrentMois(Boolean recurrentMois) {
        this.recurrentMois = recurrentMois;
    }

}
