package fr.cpbstats.model;

// Generated 29 juin 2015 23:26:12 by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Objectif generated by hbm2java
 */
@Entity
@Table(name = "objectif")
public class Objectif implements java.io.Serializable {

    /** The serialVersionUID. */
    private static final long serialVersionUID = 8776364241462090692L;
    private Integer id;
    private Utilisateur utilisateur;
    private String libelle;
    private List<ObjectifExercice> objectifExercices = new ArrayList<ObjectifExercice>(0);

    public Objectif() {}

    public Objectif(Integer id, Utilisateur utilisateur) {
        this.id = id;
        this.utilisateur = utilisateur;
    }

    public Objectif(Integer id, Utilisateur utilisateur, String libelle,
            List<ObjectifExercice> objectifExercices) {
        this.id = id;
        this.utilisateur = utilisateur;
        this.libelle = libelle;
        this.objectifExercices = objectifExercices;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "utilisateur_id", nullable = false)
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }

    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    @Column(name = "libelle", length = 145)
    public String getLibelle() {
        return this.libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "objectif")
    public List<ObjectifExercice> getObjectifExercices() {
        return this.objectifExercices;
    }

    public void setObjectifExercices(List<ObjectifExercice> objectifExercices) {
        this.objectifExercices = objectifExercices;
    }

}
