package fr.cpbstats.model;

// Generated 18 juil. 2015 20:17:29 by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Objectif generated by hbm2java
 */
@Entity
@Table(name = "objectif")
public class Objectif implements java.io.Serializable {

    /** The serialVersionUID. */
    private static final long serialVersionUID = 5459487511644620153L;

    private Integer id;
    private Utilisateur utilisateur;
    private String libelle;
    private Date dateDebut;
    private Date dateFin;
    private List<ObjectifExercice> objectifExercices = new ArrayList<ObjectifExercice>(0);

    public Objectif() {}

    public Objectif(Utilisateur utilisateur, Date dateDebut) {
        this.utilisateur = utilisateur;
        this.dateDebut = dateDebut;
    }

    public Objectif(Utilisateur utilisateur, String libelle, Date dateDebut, Date dateFin,
            List<ObjectifExercice> objectifExercices) {
        this.utilisateur = utilisateur;
        this.libelle = libelle;
        this.dateDebut = dateDebut;
        this.dateFin = dateFin;
        this.objectifExercices = objectifExercices;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "utilisateur_id", nullable = false)
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }

    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    @Column(name = "libelle", length = 145)
    public String getLibelle() {
        return this.libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "date_debut", nullable = false, length = 10)
    public Date getDateDebut() {
        return this.dateDebut;
    }

    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "date_fin", length = 10)
    public Date getDateFin() {
        return this.dateFin;
    }

    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "objectif")
    public List<ObjectifExercice> getObjectifExercices() {
        return this.objectifExercices;
    }

    public void setObjectifExercices(List<ObjectifExercice> objectifExercices) {
        this.objectifExercices = objectifExercices;
    }

}
