package fr.cpbstats.model;

// Generated 29 juin 2015 23:26:12 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ObjectifExerciceId generated by hbm2java
 */
@Embeddable
public class ObjectifExerciceId implements java.io.Serializable {

    /** The serialVersionUID. */
    private static final long serialVersionUID = -3624688367841081735L;
    private Integer objectifId;
    private Integer typeExerciceId;

    public ObjectifExerciceId() {}

    public ObjectifExerciceId(Integer objectifId, Integer typeExerciceId) {
        this.objectifId = objectifId;
        this.typeExerciceId = typeExerciceId;
    }

    @Column(name = "objectif_id", nullable = false)
    public Integer getObjectifId() {
        return this.objectifId;
    }

    public void setObjectifId(Integer objectifId) {
        this.objectifId = objectifId;
    }

    @Column(name = "type_exercice_id", nullable = false)
    public Integer getTypeExerciceId() {
        return this.typeExerciceId;
    }

    public void setTypeExerciceId(Integer typeExerciceId) {
        this.typeExerciceId = typeExerciceId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof ObjectifExerciceId))
            return false;
        ObjectifExerciceId castOther = (ObjectifExerciceId) other;

        return (this.getObjectifId() == castOther.getObjectifId())
                && (this.getTypeExerciceId() == castOther.getTypeExerciceId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getObjectifId();
        result = 37 * result + this.getTypeExerciceId();
        return result;
    }

}
