package fr.cpbstats.model;

// Generated 29 juin 2015 23:26:12 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeProfil generated by hbm2java
 */
@Entity
@Table(name = "type_profil")
public class TypeProfil implements java.io.Serializable {

    private int id;
    private String libelle;
    private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

    public TypeProfil() {}

    public TypeProfil(int id, String libelle) {
        this.id = id;
        this.libelle = libelle;
    }

    public TypeProfil(int id, String libelle, Set<Utilisateur> utilisateurs) {
        this.id = id;
        this.libelle = libelle;
        this.utilisateurs = utilisateurs;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "libelle", nullable = false, length = 45)
    public String getLibelle() {
        return this.libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "typeProfil")
    public Set<Utilisateur> getUtilisateurs() {
        return this.utilisateurs;
    }

    public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
        this.utilisateurs = utilisateurs;
    }

}
