package fr.cpbstats.model;

// Generated 29 juin 2015 23:26:12 by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TypeProfil generated by hbm2java
 */
@Entity
@Table(name = "type_profil")
public class TypeProfil implements java.io.Serializable {

    private int id;
    private String libelle;

    public TypeProfil() {}

    public TypeProfil(int id, String libelle) {
        this.id = id;
        this.libelle = libelle;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "libelle", nullable = false, length = 45)
    public String getLibelle() {
        return this.libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

}
