package fr.cpbstats.model;

// Generated 29 juin 2015 23:26:12 by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur")
public class Utilisateur implements java.io.Serializable {

    private Integer id;
    private TypeProfil typeProfil;
    private String nom;
    private String prenom;
    private String login;
    private String password;
    private Set<Objectif> objectifs = new HashSet<Objectif>(0);
    private Set<Exercice> exercices = new HashSet<Exercice>(0);
    private Set<Rencontre> rencontres = new HashSet<Rencontre>(0);

    public Utilisateur() {}

    public Utilisateur(Integer id, TypeProfil typeProfil) {
        this.id = id;
        this.typeProfil = typeProfil;
    }

    public Utilisateur(Integer id, TypeProfil typeProfil, String nom, String prenom, String login,
            String password, Set<Objectif> objectifs, Set<Exercice> exercices,
            Set<Rencontre> rencontres) {
        this.id = id;
        this.typeProfil = typeProfil;
        this.nom = nom;
        this.prenom = prenom;
        this.login = login;
        this.password = password;
        this.objectifs = objectifs;
        this.exercices = exercices;
        this.rencontres = rencontres;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "type_profil_id", nullable = false)
    public TypeProfil getTypeProfil() {
        return this.typeProfil;
    }

    public void setTypeProfil(TypeProfil typeProfil) {
        this.typeProfil = typeProfil;
    }

    @Column(name = "nom", length = 45)
    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    @Column(name = "prenom", length = 45)
    public String getPrenom() {
        return this.prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    @Column(name = "login", length = 15)
    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    @Column(name = "password", length = 15)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "utilisateur")
    public Set<Objectif> getObjectifs() {
        return this.objectifs;
    }

    public void setObjectifs(Set<Objectif> objectifs) {
        this.objectifs = objectifs;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "utilisateur")
    public Set<Exercice> getExercices() {
        return this.exercices;
    }

    public void setExercices(Set<Exercice> exercices) {
        this.exercices = exercices;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "utilisateur")
    public Set<Rencontre> getRencontres() {
        return this.rencontres;
    }

    public void setRencontres(Set<Rencontre> rencontres) {
        this.rencontres = rencontres;
    }

}
